kind = "api"
previewPath = "/"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "python ../../sameer-ai-agent/app.py"

[services.production]

[services.production.build]
args = ["python", "-m", "pip", "install", "-r", "../../sameer-ai-agent/requirements.txt"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
# we don't run through pnpm to make startup faster in production
args = ["python", "../../sameer-ai-agent/app.py"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/"
